CREATE TABLE mc_list_model (
    id SERIAL PRIMARY KEY,
    id_list INTEGER,
    Zone VARCHAR(255),
    Line VARCHAR(255),
    Op_No VARCHAR(255),
    OP_Part VARCHAR(255),
    Unique_OPNO VARCHAR(255),
    Mapping_Layout VARCHAR(255),
    Machine_No VARCHAR(255),
    MC_Part VARCHAR(255),
    Unique_MCNO VARCHAR(255),
    J_L VARCHAR(255),
    Operation_Name VARCHAR(255),
    Machine_Maker VARCHAR(255),
    Machine_Name VARCHAR(255),
    Model VARCHAR(255),
    Serial_No VARCHAR(255),
    Date_Of_Mfg DATE
);

INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('1', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', 'STSC-0033', 'n', 'STSC-0033', 'LOCAL', 'OIL MIST COLLECTOR', 'AREE ENGINEERING SUPPLY', 'MIST COLLECTOR', '-', '-', '1-Nov-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('10', 'BLOCK : D3', 'BLOCK', '30', '-', 'OP30', 'D3Block_3', 'STTR-0028', '-', 'STTR-0028', 'JAPAN', 'MILLING ALL JOURNAL JOINT FACE (9st)', 'JTEKT', 'TRANFER MACNINE', '-', 'T-8298', '1-May-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('100', 'BLOCK : D3', 'BLOCK', '580', '-', 'OP580', 'D3Block_62', 'STGR-0066', '-', 'STGR-0066', 'JAPAN', 'ROUGH FINE PLATEAU CYLINDER BORE', 'JTEKT', 'HORNING M/C', '-', 'M-8153', '1-May-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('101', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', 'STSC-0057', 'n', 'STSC-0057', 'LOCAL', 'OIL MIST COLLECTOR', 'AREE ENGINEERING SUPPLY', 'MIST COLLECTOR', '-', '-', '1-Nov-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('102', 'BLOCK : D3', 'BLOCK', '900', '20', 'OP900-20', '', 'STCK-0098', '20', 'STCK-0098-20', 'LOCAL', 'CONVEYOR M/C TO M/C & TURN TABLE', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('103', 'BLOCK : D3', 'BLOCK', '590', '-', 'OP590', 'D3Block_63', 'STTS-0267', '-', 'STTS-0267', 'LOCAL', 'STAMP NO. BORE', 'TOSEI ENGINEERING', 'MEASURING M/C', '45709TH', '08 มี.ค. 2553', '1-Aug-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('104', 'BLOCK : D3', 'BLOCK', '900', '21', 'OP900-21', '', 'STCK-0098', '21', 'STCK-0098-21', 'LOCAL', 'CONVEYOR M/C TO M/C & TURN OVER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('105', 'BLOCK : D3', 'BLOCK', '600', '-', 'OP600', 'D3Block_64', 'STWB-0126', '-', 'STWB-0126', 'LOCAL', 'FINAL WASHING', 'KITO', 'WASHING M/C', '-', 'RI-3090', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('106', 'BLOCK : D3', 'BLOCK', '900', '22', 'OP900-22', '', 'STCK-0098', '22', 'STCK-0098-22', 'LOCAL', 'CONVEYOR M/C TO M/C & TURN OVER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('107', 'BLOCK : D3', 'BLOCK', '610', '-', 'OP610', 'D3Block_65', 'STTS-0268', '-', 'STTS-0268', 'JAPAN', 'PERSS FITTING TIGHT PLUG & TEST LEAK W/J AND O/H', 'YASUNAGA', 'LEAK TESTER', '-', 'M-4297', '1-Jul-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('108', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', 'STSC-0047', 'n', 'STSC-0047', 'LOCAL', 'OIL MIST COLLECTOR', 'AREE ENGINEERING SUPPLY', 'MIST COLLECTOR', '-', '-', '1-Nov-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('109', 'BLOCK : D3', 'BLOCK', '930', '6', 'OP930-6', '', 'STZY-0337', '6', 'STZY-0337-6', 'LOCAL', 'ANDON BOX No.6', 'MEIWA e', 'ANDON', '-', '-', '1-Oct-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('11', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', 'STSC-0045', 'n', 'STSC-0045', 'LOCAL', 'OIL MIST COLLECTOR', 'AREE ENGINEERING SUPPLY', 'MIST COLLECTOR', '-', '-', '1-Nov-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('110', 'BLOCK : D3', 'BLOCK', '930', '7', 'OP930-7', '', 'STZY-0337', '7', 'STZY-0337-7', 'LOCAL', 'ANDON BOX No.7', 'MEIWA e', 'ANDON', '-', '-', '1-Oct-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('111', 'BLOCK : D3', 'BLOCK', '900', '23', 'OP900-23', '', 'STCK-0098', '23', 'STCK-0098-23', 'LOCAL', 'CONVEYOR M/C TO M/C & LIFTER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('112', 'BLOCK : D3', 'BLOCK', '900', '24A', 'OP900-24A', '', 'STCK-0098', '24-1', 'STCK-0098-24-1', 'LOCAL', 'CONVEYOR M/C TO M/C & TRANVERSER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('113', 'BLOCK : D3', 'BLOCK', '900', '24B', 'OP900-24B', '', 'STCK-0098', '24-2', 'STCK-0098-24-2', 'LOCAL', 'CONVEYOR M/C TO M/C & STOCK CONV. FINISH', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('114', 'BLOCK : D3', 'BLOCK', '940', '-', 'OP940', '', '-', '-', '', 'LOCAL', 'SETTING GAUGE (Q-GATE)', '-', 'MEASURING M/C (CMM)', '-', '-', null);
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('12', 'BLOCK : D3', 'BLOCK', '900', '4', 'OP900-4', 'D3Block_69', 'STCK-0098', '4', 'STCK-0098-4', 'LOCAL', 'CONVEYOR M/C TO M/C', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('13', 'BLOCK : D3', 'BLOCK', '40', '-', 'OP40', 'D3Block_4', 'STBR-0032', '-', 'STBR-0032', 'JAPAN', 'ROUGH BORING (1#,2#,3#,4#) (5st)', 'JTEKT', 'MULTI SPINDLE M/C', '-', 'T-8299', '1-May-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('14', 'BLOCK : D3', 'BLOCK', '900', '5A', 'OP900-5A', 'D3Block_70', 'STCK-0098', '1-พ.ค.', 'STCK-0098-5-1', 'LOCAL', 'CONVEYOR M/C TO M/C & TRANVERSER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('15', 'BLOCK : D3', 'BLOCK', '900', '5B', 'OP900-5B', 'D3Block_71', 'STCK-0098', '2-พ.ค.', 'STCK-0098-5-2', 'LOCAL', 'CONVEYOR M/C TO M/C & STOCK CONVEYOR', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('16', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', 'STSC-0048', 'n', 'STSC-0048', 'LOCAL', 'OIL MIST COLLECTOR', 'AREE ENGINEERING SUPPLY', 'MIST COLLECTOR', '-', '-', '1-Nov-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('17', 'BLOCK : D3', 'BLOCK', '50', '1', 'OP50-1', 'D3Block_5', 'STZY-0326', '-', 'STZY-0326', 'JAPAN', 'LOADING & POSTURE CONV.', 'SHINMEI INDUSTRY', 'LOADING', '-', 'M-8300A', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('18', 'BLOCK : D3', 'BLOCK', '50', '2', 'OP50-2', 'D3Block_6', 'STSP-0667', '-', 'STSP-0667', 'JAPAN', 'ROUGH BORING RH. FACE OIL RETURN & WATER PLUG', 'JTEKT', 'MULTI SPINDLE M/C', 'DS006C', 'M-8300', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('19', 'BLOCK : D3', 'BLOCK', '50', '3', 'OP50-3', 'D3Block_7', 'STSP-0668', '-', 'STSP-0668', 'JAPAN', 'MILLING EX. MANIFOLD STAY FIXING FACE RH. FACE', 'JTEKT', '1 SP NC M/C', 'TH555G5', 'MH-4897', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('2', 'BLOCK : D3', 'BLOCK', '900', '1', 'OP900-1', 'D3Block_66', 'STCK-0098', '1', 'STCK-0098-1', 'LOCAL', 'CONVEYOR RAW MAT.', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('20', 'BLOCK : D3', 'BLOCK', '50', '4', 'OP50-4', 'D3Block_8', 'STSP-0669', '-', 'STSP-0669', 'JAPAN', 'DRILLING LINE IDENTIFICATION HOLE', 'JTEKT', '1 SP NC M/C', 'TH555G5', 'MH-4880', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('21', 'BLOCK : D3', 'BLOCK', '50', '5', 'OP50-5', 'D3Block_9', 'STSP-0670', '-', 'STSP-0670', 'JAPAN', 'MILLING MOUNTING BRACKET & SUPPLY PUMP LH. FACE', 'JTEKT', '1 SP NC M/C', 'TH555G5', 'MH-4881', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('22', 'BLOCK : D3', 'BLOCK', '50', '6', 'OP50-6', 'D3Block_10', 'STSP-0671', '-', 'STSP-0671', 'JAPAN', 'MILLING LH. EGR COOLER FIXING FACE & REAR AND PLATE', 'JTEKT', '1 SP NC M/C', 'TH555G5', 'MH-4882', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('23', 'BLOCK : D3', 'BLOCK', '50', '7', 'OP50-7', 'D3Block_11', 'STZY-0327', '-', 'STZY-0327', 'JAPAN', 'UNLOADING & POSTURE CONV.', 'SHINMEI INDUSTRY', 'UNLOADING', '-', '-', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('24', 'BLOCK : D3', 'BLOCK', '900', '6', 'OP900-6', '', 'STCK-0098', '6', 'STCK-0098-6', 'LOCAL', 'CONVEYOR M/C TO M/C', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('25', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', 'STSC-0046', 'n', 'STSC-0046', 'LOCAL', 'OIL MIST COLLECTOR', 'AREE ENGINEERING SUPPLY', 'MIST COLLECTOR', '-', '-', '1-Nov-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('26', 'BLOCK : D3', 'BLOCK', '930', '3', 'OP930-3', '', 'STZY-0337', '3', 'STZY-0337-3', 'LOCAL', 'ANDON BOX No.3', 'MEIWA e', 'ANDON', '-', '-', '1-Oct-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('27', 'BLOCK : D3', 'BLOCK', '60', '1', 'OP60-1', 'D3Block_12', 'STTR-0029', '-', 'STTR-0029', 'JAPAN', 'LOADING & POSTURE CONV. (1st)', 'JTEKT (SHINMEI )', 'LOADING', '-', 'M-8301A', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('28', 'BLOCK : D3', 'BLOCK', '60', '2', 'OP60-2', '', '', '-', '', 'JAPAN', 'GROOVING OIL SUPPLY OF CRANK SHAFT (2st)', 'JTEKT', 'MILLING  M/C', '-', 'M-8301B', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('29', 'BLOCK : D3', 'BLOCK', '60', '3', 'OP60-3', '', '', '-', '', 'JAPAN', 'GROOVING OIL SUPPLY OF CRANK SHAFT (3st)', 'JTEKT', 'MILLING  M/C', '-', 'M-8302', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('3', 'BLOCK : D3', 'BLOCK', '10', '-', 'OP10', 'D3Block_1', 'STTR-0026', '-', 'STTR-0026', 'JAPAN', 'MILLING MACHINE DATUM FACE (4st)', 'JTEKT', 'TRANFER MACNINE', '-', 'T-8296', '1-May-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('30', 'BLOCK : D3', 'BLOCK', '60', '4', 'OP60-4', '', '', '-', '', 'JAPAN', 'GROOVING OIL SUPPLY OF CRANK SHAFT (4st)', 'JTEKT', 'MILLING  M/C', '-', 'M-8303', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('31', 'BLOCK : D3', 'BLOCK', '60', '5', 'OP60-5', '', '', '-', '', 'JAPAN', 'UNLOADING & POSTURE CONV. (5st)', 'JTEKT (SHINMEI )', 'UNLOADING', '-', '-', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('32', 'BLOCK : D3', 'BLOCK', '900', '7', 'OP900-7', 'D3Block_72', 'STCK-0098', '7', 'STCK-0098-7', 'LOCAL', 'CONVEYOR M/C TO M/C', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('33', 'BLOCK : D3', 'BLOCK', '70', '-', 'OP70', 'D3Block_13', 'STTR-0030', '-', 'STTR-0030', 'JAPAN', 'DRILLING SUB & MAIN OIL HOLE (8st)', 'JTEKT', 'MULTI SPINDLE M/C', 'STR-84 / TYG-8256', 'TYG-8304', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('34', 'BLOCK : D3', 'BLOCK', '930', '-', 'OP930', '', 'STZY-0337', '-', 'STZY-0337', 'LOCAL', 'ANDON MAIN', 'MEIWA e', 'ANDON', '-', '-', '1-Oct-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('35', 'BLOCK : D3', 'BLOCK', '900', '8', 'OP900-8', 'D3Block_73', 'STCK-0098', '8', 'STCK-0098-8', 'LOCAL', 'CONVEYOR STOCK AUTO1 TO AUTO2', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('36', 'BLOCK : D3', 'BLOCK', '80', '-', 'OP80', 'D3Block_14', 'STSP-0672', '-', 'STSP-0672', 'JAPAN', 'ROUGH FACING SURFACE OIL HOLE & SUB OIL HOLE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4883', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('37', 'BLOCK : D3', 'BLOCK', '90', '-', 'OP90', 'D3Block_15', 'STSP-0673', '-', 'STSP-0673', 'JAPAN', 'DRILLING MAIN & SUB OIL HOLE PLUG', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4884', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('38', 'BLOCK : D3', 'BLOCK', '100', '-', 'OP100', 'D3Block_16', 'STSP-0674', '-', 'STSP-0674', 'JAPAN', 'REAMING WATER PLUG HOLE FR. FACE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4885', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('39', 'BLOCK : D3', 'BLOCK', '110', '-', 'OP110', 'D3Block_17', 'STSP-0675', '-', 'STSP-0675', 'JAPAN', 'DRILLING OIL FILTER OIL SUPPLY HOLE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4886', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('4', 'BLOCK : D3', 'BLOCK', '900', '2', 'OP900-2', 'D3Block_67', 'STCK-0098', '2', 'STCK-0098-2', 'LOCAL', 'CONVEYOR M/C TO M/C', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('40', 'BLOCK : D3', 'BLOCK', '120', '-', 'OP120', 'D3Block_18', 'STSP-0676', '-', 'STSP-0676', 'JAPAN', 'DRILLING OIL COOLER & OIL FILTER FIXING HOLE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH506C', 'M-8305', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('41', 'BLOCK : D3', 'BLOCK', '130', '-', 'OP130', 'D3Block_19', 'STSP-0677', '-', 'STSP-0677', 'JAPAN', 'REAMING PLUG HOLE FOR MAIN OIL HOLE FR. FACE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4887', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('42', 'BLOCK : D3', 'BLOCK', '140', '-', 'OP140', 'D3Block_20', 'STSP-0678', '-', 'STSP-0678', 'JAPAN', 'TAPPING TURBO SUPPLY OIL HOLE FIXING HOLE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH506C', 'M-8306', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('43', 'BLOCK : D3', 'BLOCK', '150', '-', 'OP150', 'D3Block_21', 'STSP-0679', '-', 'STSP-0679', 'JAPAN', 'REAMING WATER PLUG RH. FACE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH506C', 'M-8307', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('44', 'BLOCK : D3', 'BLOCK', '160', '-', 'OP160', 'D3Block_22', 'STSP-0680', '-', 'STSP-0680', 'JAPAN', 'ROUGH BORING WATER PLUG & BLOWBY HOLE LH. FACE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH506C', 'M-8308', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('45', 'BLOCK : D3', 'BLOCK', '170', '-', 'OP170', 'D3Block_23', 'STSP-0681', '-', 'STSP-0681', 'JAPAN', 'DRILLING FIXING HOLE LH.', 'JTEKT', 'MULTI SPINDLE M/C', 'DH506C', 'M-8309', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('46', 'BLOCK : D3', 'BLOCK', '900', '9', 'OP900-9', 'D3Block_74', 'STCK-0098', '9', 'STCK-0098-9', 'LOCAL', 'CONVEYOR M/C TO M/C', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('47', 'BLOCK : D3', 'BLOCK', '180', '-', 'OP180', 'D3Block_24', 'STSP-0682', '-', 'STSP-0682', 'JAPAN', 'TAPPING LH. FACE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH506C', 'M-8310', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('48', 'BLOCK : D3', 'BLOCK', '190', '-', 'OP190', 'D3Block_25', 'STSP-0683', '-', 'STSP-0683', 'JAPAN', 'DRILLING FIXING HOLE RR.', 'JTEKT', 'MULTI SPINDLE M/C', 'DH506C', 'M-8311', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('49', 'BLOCK : D3', 'BLOCK', '200', '-', 'OP200', 'D3Block_26', 'STSP-0684', '-', 'STSP-0684', 'JAPAN', 'CHAMFERING CHAIN SLIPPER FIXING HOLE FR. FACE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH406C', 'M-8312', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('5', 'BLOCK : D3', 'BLOCK', '930', '2', 'OP930-2', '', 'STZY-0337', '2', 'STZY-0337-2', 'LOCAL', 'ANDON BOX No.2', 'MEIWA e', 'ANDON', '-', '-', '1-Oct-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('50', 'BLOCK : D3', 'BLOCK', '900', '10', 'OP900-10', 'D3Block_75', 'STCK-0098', '10', 'STCK-0098-10', 'LOCAL', 'CONVEYOR M/C TO M/C & TRANVERSER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('51', 'BLOCK : D3', 'BLOCK', '210', '-', 'OP210', 'D3Block_27', 'STSP-0685', '-', 'STSP-0685', 'JAPAN', 'TAPPUNG EACH HOLE FR. FACE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH506C', 'M-8313', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('52', 'BLOCK : D3', 'BLOCK', '215', '-', 'OP215', 'D3Block_28', 'STMI-0076', '-', 'STMI-0076', 'JAPAN', 'FINE MILLING FR. AND RR.', 'JTEKT', 'MULTI SPINDLE M/C', '-', 'M-8323', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('53', 'BLOCK : D3', 'BLOCK', '900', '11A', 'OP900-11A', 'D3Block_76', 'STCK-0098', '1-พ.ย.', 'STCK-0098-11-1', 'LOCAL', 'CONVEYOR M/C TO M/C & TURN OVER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('54', 'BLOCK : D3', 'BLOCK', '220', '-', 'OP220', 'D3Block_29', 'STSP-0686', '-', 'STSP-0686', 'JAPAN', 'CHAMFERING BOTTOM CYLINDER BORES', 'JTEKT', '1 SP NC M/C', 'TH555G5', 'MH-4910', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('55', 'BLOCK : D3', 'BLOCK', '230', '-', 'OP230', 'D3Block_30', 'STSP-0687', '-', 'STSP-0687', 'JAPAN', 'MILLING OILJET FITTING FACE', 'JTEKT', '1 SP NC M/C', 'TH555G5', 'MH-4911', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('56', 'BLOCK : D3', 'BLOCK', '240', '-', 'OP240', 'D3Block_31', 'STSP-0688', '-', 'STSP-0688', 'JAPAN', 'REAMER INSERTINON HOLE FOR POSTON OIL JET', 'JTEKT', 'MULTI SPINDLE M/C', 'DH406C', 'M-8324', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('57', 'BLOCK : D3', 'BLOCK', '250', '-', 'OP250', 'D3Block_32', 'STSP-0689', '-', 'STSP-0689', 'JAPAN', 'TAPPING POSTON OIL JET FIXING HOLE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH406C', 'M-8325', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('58', 'BLOCK : D3', 'BLOCK', '260', '-', 'OP260', 'D3Block_33', 'STSP-0690', '-', 'STSP-0690', 'JAPAN', 'DRILLING CHAIN OILJET OIL SUPPLY HOLE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4912', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('59', 'BLOCK : D3', 'BLOCK', '270', '-', 'OP270', 'D3Block_34', 'STSP-0691', '-', 'STSP-0691', 'JAPAN', 'DRILLING WATER BYPASS HOLE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4913', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('6', 'BLOCK : D3', 'BLOCK', '20', '-', 'OP20', 'D3Block_2', 'STTR-0027', '-', 'STTR-0027', 'JAPAN', 'DRILLING DATUM HOLE ON OILPAN FACE (11st)', 'JTEKT', 'TRANFER MACNINE', '-', 'T-8297', '1-May-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('60', 'BLOCK : D3', 'BLOCK', '280', '-', 'OP280', 'D3Block_35', 'STSP-0692', '-', 'STSP-0692', 'JAPAN', 'DRILLING OIL SUPPLY HOLE FOR CYLINDER HEAD', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4914', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('61', 'BLOCK : D3', 'BLOCK', '290', '-', 'OP290', 'D3Block_36', 'STSP-0693', '-', 'STSP-0693', 'JAPAN', 'DRILLING & TAPPING OIL SRTAINER FIXING HOLE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH406C', 'M-8326', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('62', 'BLOCK : D3', 'BLOCK', '300', '-', 'OP300', 'D3Block_37', 'STSP-0694', '-', 'STSP-0694', 'JAPAN', 'DRILLING & CHAMFERING CRANK CAP FIXING BOLT HOLE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH406C', 'M-8327', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('63', 'BLOCK : D3', 'BLOCK', '900', '12A', 'OP900-12A', '', 'STCK-0098', '1-ธ.ค.', 'STCK-0098-12-1', 'LOCAL', 'CONVEYOR M/C TO M/C & TRANVERSER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('64', 'BLOCK : D3', 'BLOCK', '900', '12B', 'OP900-12B', '', 'STCK-0098', '2-ธ.ค.', 'STCK-0098-12-2', 'LOCAL', 'CONVEYOR M/C TO M/C & STOCK CONVEYOR', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('65', 'BLOCK : D3', 'BLOCK', '330', '-', 'OP330', 'D3Block_38', 'STSP-0695', '-', 'STSP-0695', 'JAPAN', 'TAPPING OILPAN FIXING HOLE', 'JTEKT', 'MULTI SPINDLE M/C', 'DH406C', 'M-8328', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('66', 'BLOCK : D3', 'BLOCK', '340', '-', 'OP340', 'D3Block_39', 'STSP-0696', '-', 'STSP-0696', 'JAPAN', 'DRILLING & CHAMFER OIL PASSAGE HOLE OF CRANK', 'JTEKT', 'MULTI SPINDLE M/C', 'DH406C', 'M-8329', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('67', 'BLOCK : D3', 'BLOCK', '350', '-', 'OP350', 'D3Block_40', 'STSP-0697', '-', 'STSP-0697', 'JAPAN', 'MILLING SURFACE FOR SERIAL STAMP ENGING NO.', 'JTEKT', 'MULTI SPINDLE M/C', 'DH406C', 'M-8330', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('68', 'BLOCK : D3', 'BLOCK', '360', '-', 'OP360', 'D3Block_41', 'STSP-0698', '-', 'STSP-0698', 'JAPAN', 'DRILLING & REAMING OIL LEVEL GAUGE FIXING HOLE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4915', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('69', 'BLOCK : D3', 'BLOCK', '370', '-', 'OP370', 'D3Block_42', 'STSP-0699', '-', 'STSP-0699', 'JAPAN', 'DRILLING SUPPLY OIL HOLE FOR MAIL OIL HOLE RH. FACE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4916', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('7', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', 'STSC-0038', 'n', 'STSC-0038', 'LOCAL', 'OIL MIST COLLECTOR', 'AREE ENGINEERING SUPPLY', 'MIST COLLECTOR', '-', '-', '1-Nov-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('70', 'BLOCK : D3', 'BLOCK', '930', '4', 'OP930-4', '', 'STZY-0337', '1', 'STZY-0337-1', 'LOCAL', 'ANDON BOX No.1', 'MEIWA e', 'ANDON', '-', '-', '1-Oct-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('71', 'BLOCK : D3', 'BLOCK', '380', '-', 'OP380', 'D3Block_43', 'STSP-0700', '-', 'STSP-0700', 'JAPAN', 'GROOVING O RING RH. FACE DAI. 26.3 AND 34', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4917', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('72', 'BLOCK : D3', 'BLOCK', '390', '-', 'OP390', 'D3Block_44', 'STSP-0701', '-', 'STSP-0701', 'JAPAN', 'DRILLING HEAD BOLT HOLE DIA. 15 AND 14', 'JTEKT', 'MULTI SPINDLE M/C', 'DS006C', 'M-8331', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('73', 'BLOCK : D3', 'BLOCK', '400', '-', 'OP400', 'D3Block_45', 'STSP-0702', '-', 'STSP-0702', 'JAPAN', 'DRILLING HEAD BOLT HOLE DIA. 12.5 AND 14', 'JTEKT', 'MULTI SPINDLE M/C', 'DS006C', 'M-8332', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('74', 'BLOCK : D3', 'BLOCK', '410', '-', 'OP410', 'D3Block_46', 'STSP-0703', '-', 'STSP-0703', 'JAPAN', 'DRILLING HEAD BOLT HOLE DIA.10.8', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4918', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('75', 'BLOCK : D3', 'BLOCK', '420', '-', 'OP420', 'D3Block_47', 'STSP-0704', '-', 'STSP-0704', 'JAPAN', 'TAPPING HEAD BOLT HOLE M12 AND M14', 'JTEKT', 'MULTI SPINDLE M/C', 'DS006C', 'M-8333', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('76', 'BLOCK : D3', 'BLOCK', '900', '11B', 'OP900-11B', 'D3Block_77', 'STCK-0098', '2-พ.ย.', 'STCK-0098-11-2', 'LOCAL', 'CONVEYOR M/C TO M/C & TURN OVER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('77', 'BLOCK : D3', 'BLOCK', '430', '-', 'OP430', 'D3Block_48', 'STSP-0705', '-', 'STSP-0705', 'JAPAN', 'REAMING CHAIN SLIPPER FIXING PIN HOLE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4919', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('78', 'BLOCK : D3', 'BLOCK', '900', '13', 'OP900-13', '', 'STCK-0098', '13', 'STCK-0098-13', 'LOCAL', 'CONVEYOR M/C TO M/C & TRANVERSER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('79', 'BLOCK : D3', 'BLOCK', '440', '-', 'OP440', 'D3Block_49', 'STSP-0706', '-', 'STSP-0706', 'JAPAN', 'REAMING PLUG HOLE (35) AND MAIN & SUB OIL HOLE PLUG RR.', 'JTEKT', 'MULTIPLE SP NC M/C', 'DH406C', 'M-8834', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('8', 'BLOCK : D3', 'BLOCK', '900', '3', 'OP900-3', 'D3Block_68', 'STCK-0098', '3', 'STCK-0098-3', 'LOCAL', 'CONVEYOR M/C TO M/C & TRANVERSER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('80', 'BLOCK : D3', 'BLOCK', '460', '-', 'OP460', 'D3Block_50', 'STSP-0707', '-', 'STSP-0707', 'JAPAN', 'GROOVING GASKET FR. FACE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4920', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('81', 'BLOCK : D3', 'BLOCK', '470', '-', 'OP470', 'D3Block_51', 'STSP-0708', '-', 'STSP-0708', 'JAPAN', 'FACING SURFACE FOR OIL SUPPLY HOLE', 'JTEKT', '1 SP NC M/C', 'TH555G4', 'MH-4921', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('82', 'BLOCK : D3', 'BLOCK', '900', '14', 'OP900-14', '', 'STCK-0098', '14', 'STCK-0098-14', 'LOCAL', 'CONVEYOR M/C TO M/C & TURN OVER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('83', 'BLOCK : D3', 'BLOCK', '480', '-', 'OP480', 'D3Block_52', 'STMM-0044', '-', 'STMM-0044', 'LOCAL', 'DEBURRING EACH OIL PASSAGE HOLE', 'KRUZE', 'DEBURRING M/C', '-', 'TA-0127', '1-Jul-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('84', 'BLOCK : D3', 'BLOCK', '490', '-', 'OP490', 'D3Block_53', 'STWB-0125', '-', 'STWB-0125', 'JAPAN', 'MIDDLE WASHING', 'KITO', 'WASHING M/C', '-', 'RC-0198', '1-May-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('85', 'BLOCK : D3', 'BLOCK', '500', '-', 'OP500', 'D3Block_54', 'STZK-0195', '-', 'STZK-0195', 'LOCAL', 'CHECKING HOLE OF LOWER FACE', 'TATEYAMA', 'CHECKING HOLE M/C', '-', 'TF2755-96', '1-Aug-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('86', 'BLOCK : D3', 'BLOCK', '510', '-', 'OP510', 'D3Block_55', 'STTS-0266', '-', 'STTS-0266', 'JAPAN', 'LEAK TEST W/J', 'YASUNAGA', 'LEAK TESTER', '-', 'M-4296', '1-Jul-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('87', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', '-', '-', '', 'LOCAL', 'CONVEYOR SUPPLY CRANK CAP', '-', 'CONVEYOR SUPPLY PART', '-', '-', null);
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('88', 'BLOCK : D3', 'BLOCK', '520', '-', 'OP520', 'D3Block_56', 'STAT-0038', '-', 'STAT-0038', 'LOCAL', 'PRESS FITTING CRANK SHAFT BEARING', 'GIKEN', 'PRESS FITTING M/C', '-', '14-MGSR-9MU', '1-Aug-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('89', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', '-', '-', '', 'LOCAL', 'CONVEYOR SUPPLY CRANK CAP', '-', 'CONVEYOR SUPPLY PART', '-', '-', null);
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('9', 'BLOCK : D3', 'BLOCK', '930', '5', 'OP930-5', '', 'STZY-0337', '5', 'STZY-0337-5', 'LOCAL', 'ANDON BOX No.5', 'MEIWA e', 'ANDON', '-', '-', '1-Oct-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('90', 'BLOCK : D3', 'BLOCK', '530', '-', 'OP530', 'D3Block_57', 'STAM-0163', '-', 'STAM-0163', 'LOCAL', 'STAMPING CRANK SHAFT CAP NO.', 'GIKEN', 'TIGHTING M/C', '-', '14-MGSR-10MU', '1-Aug-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('91', 'BLOCK : D3', 'BLOCK', '900', '16', 'OP900-16', '', 'STCK-0098', '16', 'STCK-0098-16', 'LOCAL', 'CONVEYOR M/C TO M/C & STOCK CONVEYOR', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('92', 'BLOCK : D3', 'BLOCK', '540', '-', 'OP540', 'D3Block_58', 'STBR-0033', '-', 'STBR-0033', 'JAPAN', 'FING BORING CRANK SHAFT HOLE (7st)', 'JTEKT', 'COMPOUND SPECIAL MACHINE', '-', 'T-8336', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('93', 'BLOCK : D3', 'BLOCK', '900', '17', 'OP900-17', '', 'STCK-0098', '17', 'STCK-0098-17', 'LOCAL', 'CONVEYOR M/C TO M/C & TURN OVER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('94', 'BLOCK : D3', 'BLOCK', '-', '-', '', '', 'STSC-0056', 'n', 'STSC-0056', 'LOCAL', 'OIL MIST COLLECTOR', 'AREE ENGINEERING SUPPLY', 'MIST COLLECTOR', '-', '-', '1-Nov-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('95', 'BLOCK : D3', 'BLOCK', '550', '-', 'OP550', 'D3Block_59', 'STMI-0077', '-', 'STMI-0077', 'JAPAN', 'FINE MILLING HEAD JOINT FACE', 'JTEKT', 'MILLING  M/C', '-', 'M-8335', '1-Jun-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('96', 'BLOCK : D3', 'BLOCK', '900', '18', 'OP900-18', '', 'STCK-0098', '18', 'STCK-0098-18', 'LOCAL', 'CONVEYOR M/C TO M/C', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('97', 'BLOCK : D3', 'BLOCK', '560', '-', 'OP560', 'D3Block_60', 'STMM-0045', '-', 'STMM-0045', 'LOCAL', 'DEBURRING HEAD JOINT FACE', 'KRUZE', 'DEBURRING M/C', '-', 'TA-0128', '1-Jul-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('98', 'BLOCK : D3', 'BLOCK', '570', '-', 'OP570', 'D3Block_61', 'STBR-0015', '-', 'STBR-0015', 'JAPAN', 'FINE BORING CYLINDER BLOCK (4st)', 'JTEKT', 'BORING M/C', '-', 'M-8130', '1-Feb-2014 ');
INSERT INTO "mc_list_model" ("id_list", "zone", "line", "op_no", "op_part", "unique_opno", "mapping_layout", "machine_no", "mc_part", "unique_mcno", "j/l", "operation_name", "machine_maker", "machine_name", "model", "serial_no", "date_of_mfg") VALUES ('99', 'BLOCK : D3', 'BLOCK', '900', '19', 'OP900-19', '', 'STCK-0098', '19', 'STCK-0098-19', 'LOCAL', 'CONVEYOR M/C TO M/C & STOCK CONVEYOR & TURN OVER', 'AUTO - CS (SHINMEI)', 'CONVEYOR', '-', '-', '1-Apr-2014 ');